### ISSUE TITLE
Parser preventing from build

### ISSUE THREAD

**Issue by tbelqdx** [PrimeGoose/f1-2021-udp#1]
Hello,
we are a team trying to work using you nice pkg.
The problem is that it is impossible to build for us.
Indeed, it looks like the Parser can't be used as it is in the package.
Here are the errors when we build our project after importing yours:

```
node_modules/f1-telemetry-client/build/src/index.d.ts:33:71 - error TS2702: 'Parser' only refers to a type, but is being used as a namespace here.
33     static parsePacketHeader(buffer: Buffer, bigintEnabled: boolean): Parser.Parsed<any>;
                                                                         ~~
node_modules/f1-telemetry-client/build/src/parsers/F1Parser.d.ts:8:33 - error TS2702: 'Parser' only refers to a type, but is being used as a namespace here.
8     fromBuffer(buffer: Buffer): Parser.Parsed<any>;
                                  ~~
Found 2 errors.

error Command failed with exit code 2.
```

Any idea on how to fix it?

**Comment by PrimeGoose** [comment]
the quick fix is to change the e line `fromBuffer(buffer: Buffer): Parser.Parsed<any>;`  to `fromBuffer(buffer: Buffer): Parser;` or `fromBuffer(buffer: Buffer): any;` in the node modules folder.

thank you for reporting, I will look into this.

**Comment by PrimeGoose** [comment]
updated types and did a quick test, it should work now in the 1.0.6 version
